parameters:
  mercure:
    hubs:
      default:
        url: 'http://hub.drupalmercure.lndo.site/.well-known/mercure'
        jwt:
          secret: '!ChangeMe!'
  cors.config:
    enabled: true
    allowedHeaders: [ '*' ]
    allowedMethods: [ '*' ]
    allowedOrigins: [ '*' ]
    exposedHeaders: false
    maxAge: false
    supportsCredentials: true
services:
  cache.backend.null:
    class: Drupal\Core\Cache\NullBackendFactory
