name: drupalmercure
recipe: drupal9
config:
  php: '8.1'
  composer_version: '2-latest'
  webroot: web
  xdebug: false

# Add a Mercure container
services:
  mercure:
    app_mount: false
    services:
      command: caddy run -config /etc/caddy/Caddyfile
      environment:
        MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
        MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
        SERVER_NAME: ':80'
        MERCURE_EXTRA_DIRECTIVES: |
          publish_origins *
          anonymous
          subscriptions
      image: dunglas/mercure
      ports:
        - 1337:80
    type: compose

# Add a unique URL to the mercure container
proxy:
  mercure:
    - hub.drupalmercure.lndo.site
