<?php

function article_updates_entity_delete(\Drupal\Core\Entity\EntityInterface $entity): void {
  if (!_checkArticle($entity)) return;

  _getUpdateService()->deleteUpdate($entity);
}

function article_updates_entity_update(\Drupal\Core\Entity\EntityInterface $entity): void {
  if (!_checkArticle($entity)) return;

  _getUpdateService()->editUpdate($entity);
}

function article_updates_entity_insert(\Drupal\Core\Entity\EntityInterface $entity): void {
  if (!_checkArticle($entity)) return;

  _getUpdateService()->createUpdate($entity);
}

function _checkArticle(\Drupal\Core\Entity\EntityInterface $entity): bool {
  if (!$entity instanceof \Drupal\node\NodeInterface) {
    return false;
  }

  if ($entity->bundle() !== 'article') {
    return false;
  }

  return true;
}

function _getUpdateService(): \Drupal\article_updates\ArticleUpdatesService
{
  return Drupal::service('article_updates_service');
}
